# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
apiVersion: v1
baseDomain: {{domain}}
metadata:
  name: {{cluster}}
networking:
  clusterNetwork:
  - cidr: 192.168.0.0/16
    hostPrefix: 23
  machineNetwork:
  - cidr: {{subnet}}.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: {{count - 3}}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1
platform:
  none: {}
fips: false
pullSecret: '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}'
sshKey: '{{ssh_authorized_key}}'
