# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# Copyright 2021 Nuvolaris LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# local test run with act: act -j test -e tag.json
#
name: nuvolaris-testing
on:
  push:
    tags:        
      - v**
jobs:
  test:
    name: Test nuv binaries
    runs-on: ubuntu-latest
    steps:
      - name: Get version tag
        id: version_tag
        run: |
          echo "${{ github.event.ref }}"
          GITHUB_REF=${{ github.event.ref }}
          [[ ! "$GITHUB_REF" =~ refs/tags ]] && exit
          echo "Nuv version: ${GITHUB_REF#refs/tags/}"
          echo "NUV_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2          
      - name: Build
        run: |
          bash .github/cisetup.sh
      - name: Test
        run: |
          export NUV_VERSION="${{env.NUV_VERSION}}"
          task test-nuv          


